steps:
# This step gets the secrets from Secret Manager and writes them to a .env file
- name: "gcr.io/cloud-builders/gcloud"
  id: PrepareSecrets
  entrypoint: "/bin/sh"
  args:
    - "-c"
    - |
      set -x && \
      cd graduation-project-env
      echo "JWT_SECRET=$(gcloud secrets versions access latest --secret="jwt-secret-key")" >> .env
      echo "MONGO_URI=$(gcloud secrets versions access latest --secret="mongo-cloud-uri")" >> .env
      cp .env ${_SERVICE}_service/

- name: "gcr.io/cloud-builders/docker"
  id: Build
  entrypoint: "/bin/sh"
  args:
    - "-c"
    - |
      docker build --build-arg COMMON_URL=git+https://ercecan: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@github.com/ercecan/schedule-creator-common.git -t europe-west3-docker.pkg.dev/$PROJECT_ID/grad/${_SERVICE}:$SHORT_SHA ./${_SERVICE}_service

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: "gcr.io/cloud-builders/docker"
  id: Push
  args:
    - "push"
    - "europe-west3-docker.pkg.dev/$PROJECT_ID/grad/${_SERVICE}:$SHORT_SHA"
    # [END cloudbuild]

# this step authenticates with github
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    set -x && \
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cat /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  id: Clone env repository
  entrypoint: 'bash'
  args:
  - -c
  - |
    set -x && \
    git clone --recurse-submodules git@github.com:ercecan/graduation-project-env.git && \
    cd graduation-project-env && \
    ls -a && \
    git checkout ${_SERVICE}_candidate && \
    cd ${_SERVICE} && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: gcr.io/cloud-builders/gcloud
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - -c
  - |
    set -x && \
    sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" ${_SERVICE}_service/kubernetes.yaml.tpl | \
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" > graduation-project-env/${_SERVICE}/kubernetes.yaml

- name: gcr.io/cloud-builders/git
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - -c
  - |
    set -x && \
    cd graduation-project-env/${_SERVICE} && \
    git add kubernetes.yaml && \
    git commit -m "Deploying image europe-west3-docker.pkg.dev/$PROJECT_ID/grad/${_SERVICE}:${SHORT_SHA}
    Built from commit ${COMMIT_SHA} of repository grad
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    # Push your changes
    git push
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  # pulls the secret from manager and assigns it to env variable, usable in the steps via "$$VAR_NAME"
  - versionName: projects/$PROJECT_ID/secrets/github-ssh-key/versions/latest
    env: 'SSH_KEY'
substitutions:
  _SERVICE: user
